#!/usr/bin/env bash
# Online Quran College - one-line installer for Ubuntu 22.04 / 24.04 (Docker edition).
#   curl -fsSL https://raw.githubusercontent.com/mcgary6567-lab/Codeea/main/install.sh | bash
# Installs Docker if missing, clones the repository to /opt/oqc, writes .env with generated secrets,
# starts PostgreSQL + app + Caddy (HTTPS) + nightly pg_dump, waits for the first start (migrations and
# seed happen inside the container) and prints the sign-in details.
# Overrides: OQC_REPO, OQC_BRANCH, OQC_DIR, SEED_MODE (core|demo, default core).
set -euo pipefail

REPO_URL="${OQC_REPO:-https://github.com/mcgary6567-lab/Codeea.git}"
BRANCH="${OQC_BRANCH:-main}"
INSTALL_DIR="${OQC_DIR:-/opt/oqc}"
SEED_MODE="${SEED_MODE:-core}"
SUDO=""; [ "$(id -u)" -ne 0 ] && SUDO="sudo"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

. /etc/os-release
case "${ID:-}-${VERSION_ID:-}" in
  ubuntu-22.04|ubuntu-24.04) ;;
  *) echo "This installer targets Ubuntu 22.04 / 24.04 (found ${PRETTY_NAME:-unknown}). Use docker compose by hand on other systems."; exit 1 ;;
esac

say "1/6  Base packages"
$SUDO apt-get update -qq
$SUDO apt-get install -y -qq ca-certificates curl git openssl >/dev/null

say "2/6  Docker"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | $SUDO sh
fi
$SUDO systemctl enable --now docker >/dev/null
$SUDO docker compose version >/dev/null 2>&1 || { echo "The docker compose plugin is missing (apt install docker-compose-plugin)."; exit 1; }

say "3/6  Source -> $INSTALL_DIR"
if [ -d "$INSTALL_DIR/.git" ]; then
  $SUDO git -C "$INSTALL_DIR" pull --ff-only
else
  $SUDO git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

say "4/6  Configuration"
if $SUDO test -f .env; then
  echo ".env already exists - keeping it. Delete it to generate new secrets."
else
  # stdin is the curl pipe: prompts must come from the terminal
  read -rp "Domain for HTTPS, e.g. os.example.com (leave blank for plain HTTP on port 80 - demo only): " DOMAIN </dev/tty
  read -rp "Admin e-mail (becomes the owner sign-in; blank keeps admin@oqc.local): " ADMIN_EMAIL </dev/tty
  DOMAIN="$(printf '%s' "$DOMAIN" | tr -d '[:space:]')"
  ADMIN_EMAIL="$(printf '%s' "$ADMIN_EMAIL" | tr -d '[:space:]' | tr 'A-Z' 'a-z')"

  # Only letters and digits so the values are safe in .env, URLs and shells. The app's rule for a
  # password is >= 8 characters with a letter and a digit (app/core/security.py).
  gen() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "$1"; }
  SECRET_KEY="$(openssl rand -hex 32)"
  POSTGRES_PASSWORD="$(gen 32)"
  ADMIN_PASSWORD="$(gen 14)7a"
  DEMO_PASSWORD="$(gen 12)3d"

  if [ -n "$DOMAIN" ]; then
    SITE_ADDRESS="$DOMAIN"; BASE_URL="https://$DOMAIN"; APP_ENV="production"
  else
    IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
    SITE_ADDRESS=":80"; BASE_URL="http://${IP:-127.0.0.1}"; APP_ENV="staging"   # staging: cookie works over HTTP
  fi

  $SUDO tee .env >/dev/null <<EOF
# Generated by install.sh on $(date -Is). Secrets - keep this file at mode 600.
APP_NAME="Online Quran College OS"
APP_ENV=$APP_ENV
SECRET_KEY=$SECRET_KEY
BASE_URL=$BASE_URL
# docker-compose.yml derives DATABASE_URL from this
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
# first start: what to seed. Credentials are applied by deploy_secure.py whenever these three change.
SEED_MODE=$SEED_MODE
ADMIN_PASSWORD=$ADMIN_PASSWORD
DEMO_PASSWORD=$DEMO_PASSWORD
ADMIN_EMAIL=$ADMIN_EMAIL
# reverse proxy + backups
COMPOSE_PROFILES=server
SITE_ADDRESS=$SITE_ADDRESS
BACKUP_KEEP_DAYS=30
# scheduler runs inside the single web worker; keep 1 (see docs/DEPLOYMENT.md)
WEB_CONCURRENCY=1
SCHEDULER_ENABLED=true
SESSION_HOURS=12
ACCESS_TOKEN_MINUTES=720
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_MINUTES=15
BASE_CURRENCY=PKR
DEFAULT_TIMEZONE=Asia/Karachi
VIDEO_PROVIDER=jitsi
JITSI_DOMAIN=meet.jit.si
# integrations stay simulated until filled in
WHATSAPP_TOKEN=
WHATSAPP_PHONE_ID=
GHL_API_KEY=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=noreply@${DOMAIN:-onlinequrancollege.local}
AI_PROVIDER=simulated
AI_API_KEY=
EOF
  $SUDO chmod 600 .env
fi

say "5/6  Build and start"
export GIT_COMMIT="$(git -C "$INSTALL_DIR" rev-parse --short HEAD)"
$SUDO ${SUDO:+-E} docker compose up -d --build

say "6/6  First start (migrations + seed, 1-3 minutes)"
ok=false
for _ in $(seq 1 60); do
  if $SUDO docker compose exec -T app curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then ok=true; break; fi
  sleep 5
done
[ "$ok" = true ] || { echo "The app did not become healthy. Logs:"; $SUDO docker compose logs --tail=80 app; exit 1; }

# shellcheck disable=SC1090
eval "$($SUDO grep -E '^(BASE_URL|ADMIN_EMAIL|ADMIN_PASSWORD|DEMO_PASSWORD|SEED_MODE|APP_ENV)=' .env)"
cat <<EOF

============================================================
  Online Quran College is running
  URL        : $BASE_URL
  Sign in    : ${ADMIN_EMAIL:-admin@oqc.local}
  Password   : $ADMIN_PASSWORD   (you must change it on first sign-in)
$( [ "$SEED_MODE" = "demo" ] && echo "  Demo users : teacher1@oqc.local, parent1@oqc.local, student1@oqc.local ... / $DEMO_PASSWORD" )
  Config     : $INSTALL_DIR/.env   (mode 600)
  Upgrade    : sudo $INSTALL_DIR/upgrade.sh
  Logs       : sudo docker compose -f $INSTALL_DIR/docker-compose.yml logs -f app
============================================================
EOF
[ "$APP_ENV" = "staging" ] && echo "No domain was given: the site is plain HTTP. Re-run with a domain before real use."
exit 0
