"""student journey: teacher assignments, assessment answers, recommendations

Teacher and class-time history that is never overwritten, the question-by-question evidence of an assessment, and
teacher recommendations with the action created for each. See docs/STUDENT_JOURNEY.md.

Revision ID: 070b2e62e1cc
Revises: a4d438bbecd9
Create Date: 2026-10-09 05:33:33.760445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070b2e62e1cc'
down_revision: Union[str, Sequence[str], None] = 'a4d438bbecd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('class_time', sa.String(length=10), nullable=True),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('previous_teacher_id', sa.Integer(), nullable=True),
    sa.Column('previous_time', sa.String(length=10), nullable=True),
    sa.Column('previous_days', sa.JSON(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('reason_category', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('assessment_answers',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_answers_evaluation_id'), ['evaluation_id'], unique=False)

    op.create_table('student_recommendations',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['risk_alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_recommendations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_recommendations_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('follow_up', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_column('follow_up')
        batch_op.drop_column('parent_observations')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('stage')

    with op.batch_alter_table('student_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_recommendations_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_recommendations_kind'))

    op.drop_table('student_recommendations')
    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_answers_evaluation_id'))

    op.drop_table('assessment_answers')
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_student_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_start_date'))

    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
