"""Employee Self Portal parity: employee ledger, progress status, task collaborators

Revision ID: 2d78aefa0e3f
Revises: 30408ac573e4
Create Date: 2026-09-15 02:16:41.291403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d78aefa0e3f'
down_revision: Union[str, Sequence[str], None] = '30408ac573e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_ledger_entries',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('voucher_ref', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_ledger_entries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_ledger_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_ledger_entries_source'), ['source'], unique=False)

    with op.batch_alter_table('progress_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'draft'")))
        batch_op.create_index(batch_op.f('ix_progress_notes_status'), ['status'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collaborator_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('collaborator_ids')

    with op.batch_alter_table('progress_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_notes_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('employee_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_ledger_entries_source'))
        batch_op.drop_index(batch_op.f('ix_employee_ledger_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_employee_ledger_entries_employee_id'))

    op.drop_table('employee_ledger_entries')
    # ### end Alembic commands ###
