"""attention items

The daily attention check: students, families and teachers that need a person (docs/ATTENTION.md).

Revision ID: 2f3ce7987915
Revises: 741334a89d1d
Create Date: 2026-10-09 10:29:13.675849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3ce7987915'
down_revision: Union[str, Sequence[str], None] = '741334a89d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_items',
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_source', sa.String(length=10), nullable=False),
    sa.Column('recommended', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('task_ids', sa.JSON(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('ai_run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attention_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attention_items_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_attention_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attention_items_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attention_items_subject_type'), ['subject_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attention_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attention_items_subject_type'))
        batch_op.drop_index(batch_op.f('ix_attention_items_subject_id'))
        batch_op.drop_index(batch_op.f('ix_attention_items_status'))
        batch_op.drop_index(batch_op.f('ix_attention_items_level'))

    op.drop_table('attention_items')
    # ### end Alembic commands ###
