"""Billing Management parity: balance limit, lead verification, lead closers

Revision ID: 30408ac573e4
Revises: 592b863b4bb0
Create Date: 2026-09-14 06:39:09.625519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30408ac573e4'
down_revision: Union[str, Sequence[str], None] = '592b863b4bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_closers',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pseudo_name', sa.String(length=80), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_limit', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('payment_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_remarks', sa.String(length=300), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=30), nullable=False, server_default=sa.text("'unverified'")))
        batch_op.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verifier_remarks', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_verification_status'), ['verification_status'], unique=False)
        batch_op.create_foreign_key('fk_leads_verified_by_id', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_verified_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_verification_status'))
        batch_op.drop_column('verifier_remarks')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('billing_remarks')
        batch_op.drop_column('payment_day')
        batch_op.drop_column('balance_limit')

    op.drop_table('lead_closers')
    # ### end Alembic commands ###
