"""Accounts and Configuration parity: vouchers, account heads, lookups, branch properties, gateways, WhatsApp senders, support tickets, OTP

Revision ID: 592b863b4bb0
Revises: 77ee14c26d59
Create Date: 2026-09-14 03:28:26.603831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592b863b4bb0'
down_revision: Union[str, Sequence[str], None] = '77ee14c26d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookups',
    sa.Column('app', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookups_app'), ['app'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookups_code'), ['code'], unique=True)

    op.create_table('whatsapp_senders',
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('api_status', sa.String(length=20), nullable=False),
    sa.Column('live_mode', sa.Boolean(), nullable=False),
    sa.Column('last_message_sent_at', sa.DateTime(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('messages_per_cycle', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_token', sa.String(length=120), nullable=True),
    sa.Column('qr_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup_values',
    sa.Column('lookup_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('label_urdu', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_values_lookup_id'), ['lookup_id'], unique=False)

    op.create_table('otp_configurations',
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('code_length', sa.Integer(), nullable=False),
    sa.Column('validity_minutes', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resend_after_seconds', sa.Integer(), nullable=False),
    sa.Column('required_for_roles', sa.JSON(), nullable=False),
    sa.Column('whatsapp_sender_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['whatsapp_sender_id'], ['whatsapp_senders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_gateways',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gateway_company', sa.String(length=60), nullable=False),
    sa.Column('default_transaction_fee_pct', sa.Float(), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('beneficiary_account_id', sa.Integer(), nullable=True),
    sa.Column('live_mode', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_account_id'], ['beneficiary_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('whatsapp_no', sa.String(length=30), nullable=True),
    sa.Column('ticket_type', sa.String(length=30), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('developer_remarks', sa.Text(), nullable=True),
    sa.Column('raised_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_ticket_number'), ['ticket_number'], unique=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_head', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('is_postable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('sort_no', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_type', sa.String(length=20), nullable=False, server_default=sa.text("'journal'")))
        batch_op.add_column(sa.Column('voucher_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('party_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('party_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('party_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('beneficiary_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reference_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('posted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_journal_entries_voucher_number'), ['voucher_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_voucher_type'), ['voucher_type'], unique=False)
        batch_op.create_foreign_key('fk_journal_entries_beneficiary_account_id', 'beneficiary_accounts', ['beneficiary_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_journal_entries_posted_by_id', 'users', ['posted_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('value_type', sa.String(length=20), nullable=False, server_default=sa.text("'text'")))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('is_secret', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('sort_no', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('sort_no')
        batch_op.drop_column('is_secret')
        batch_op.drop_column('is_editable')
        batch_op.drop_column('unit')
        batch_op.drop_column('value_type')
        batch_op.drop_column('label')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_entries_posted_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_journal_entries_beneficiary_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_voucher_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_voucher_number'))
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('posted_at')
        batch_op.drop_column('posted_by_id')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('reference_no')
        batch_op.drop_column('beneficiary_account_id')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('party_name')
        batch_op.drop_column('party_id')
        batch_op.drop_column('party_type')
        batch_op.drop_column('voucher_number')
        batch_op.drop_column('voucher_type')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('opening_balance')
        batch_op.drop_column('sort_no')
        batch_op.drop_column('is_postable')
        batch_op.drop_column('is_head')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))

    op.drop_table('support_tickets')
    op.drop_table('payment_gateways')
    op.drop_table('otp_configurations')
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_values_lookup_id'))

    op.drop_table('lookup_values')
    op.drop_table('whatsapp_senders')
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookups_code'))
        batch_op.drop_index(batch_op.f('ix_lookups_app'))

    op.drop_table('lookups')
    # ### end Alembic commands ###
