"""parent communication and referral follow-up

General parent contact records (direction, duration, sentiment, issue, linked referral) and the referral
eligibility date. See docs/PARENT_COMMUNICATION.md.

Revision ID: 6a50058576b1
Revises: 070b2e62e1cc
Create Date: 2026-10-09 07:09:15.077993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a50058576b1'
down_revision: Union[str, Sequence[str], None] = '070b2e62e1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=10), nullable=False, server_default=sa.text("'outbound'")))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('issue', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('issue_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('referral_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parent_contacts_referral_id', 'referrals', ['referral_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligible_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('eligible_at')

    with op.batch_alter_table('parent_contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parent_contacts_referral_id', type_='foreignkey')
        batch_op.drop_column('referral_id')
        batch_op.drop_column('issue_category')
        batch_op.drop_column('issue')
        batch_op.drop_column('sentiment')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
