"""crm automation: tags, workflows, runs, events

Revision ID: 6eb79b7d42ee
Revises: cd82be2cce8f
Create Date: 2026-10-03 08:58:41.533438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb79b7d42ee'
down_revision: Union[str, Sequence[str], None] = 'cd82be2cce8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_events',
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('runs_started', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_events_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_events_event'), ['event'], unique=False)

    op.create_table('tags',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('workflows',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('pipeline', sa.String(length=60), nullable=True),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('trigger_filter', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('exit_on', sa.JSON(), nullable=False),
    sa.Column('run_once_per_contact', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('needs', sa.String(length=200), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflows_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_trigger'), ['trigger'], unique=False)

    op.create_table('contact_tags',
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_type', 'contact_id', 'tag_id', name='uq_contact_tag')
    )
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_tags_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_tags_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(length=40), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stop_reason', sa.String(length=200), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_contact_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_contact_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_contact_tags_contact_type'))
        batch_op.drop_index(batch_op.f('ix_contact_tags_contact_id'))

    op.drop_table('contact_tags')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_trigger'))
        batch_op.drop_index(batch_op.f('ix_workflows_is_active'))
        batch_op.drop_index(batch_op.f('ix_workflows_code'))
        batch_op.drop_index(batch_op.f('ix_workflows_category'))

    op.drop_table('workflows')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_category'))

    op.drop_table('tags')
    with op.batch_alter_table('automation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_events_event'))
        batch_op.drop_index(batch_op.f('ix_automation_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_automation_events_contact_id'))

    op.drop_table('automation_events')
    # ### end Alembic commands ###
