"""ghl sync queue and log

The GoHighLevel sync queue, retry state and log (docs/GHL_INTEGRATION.md).

Revision ID: 741334a89d1d
Revises: 6a50058576b1
Create Date: 2026-10-09 09:37:22.562497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741334a89d1d'
down_revision: Union[str, Sequence[str], None] = '6a50058576b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghl_sync_jobs',
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('ghl_contact_id', sa.String(length=80), nullable=True),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ghl_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_ghl_contact_id'), ['ghl_contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ghl_sync_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghl_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_ghl_contact_id'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_direction'))
        batch_op.drop_index(batch_op.f('ix_ghl_sync_jobs_dedupe_key'))

    op.drop_table('ghl_sync_jobs')
    # ### end Alembic commands ###
