"""Human Resource parity: catalogues, entitlements, staff requests, recruitment pipeline

Revision ID: 77ee14c26d59
Revises: dee1fc82982b
Create Date: 2026-09-14 03:03:00.437812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ee14c26d59'
down_revision: Union[str, Sequence[str], None] = 'dee1fc82982b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_types',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_urdu', sa.Text(), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('basic_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('shift_group', sa.String(length=20), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_holiday_date'), ['holiday_date'], unique=False)

    op.create_table('hr_downloads',
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_panels',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_types',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_urdu', sa.Text(), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)

    op.create_table('employee_requests',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_requests_request_date'), ['request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_requests_status'), ['status'], unique=False)

    op.create_table('leave_entitlements',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('total_assigned', sa.Float(), nullable=False),
    sa.Column('consumed', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_entitlements_employee_id'), ['employee_id'], unique=False)

    op.create_table('progress_notes',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('working_date', sa.Date(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('manager_rating', sa.Integer(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('rated_by_id', sa.Integer(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_notes_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_notes_working_date'), ['working_date'], unique=False)

    op.create_table('staff_complaints',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('complaint_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('about_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_complaints_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_complaints_is_secret'), ['is_secret'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_complaints_status'), ['status'], unique=False)

    op.create_table('attendance_change_requests',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('old_check_in', sa.Time(), nullable=True),
    sa.Column('old_check_out', sa.Time(), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('new_check_in', sa.Time(), nullable=True),
    sa.Column('new_check_out', sa.Time(), nullable=True),
    sa.Column('user_remarks', sa.Text(), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['hr_attendance.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_change_requests_status'), ['status'], unique=False)

    op.create_table('job_applications',
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('application_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('nic_number', sa.String(length=30), nullable=True),
    sa.Column('cell_no', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('expected_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('hired_employee_id', sa.Integer(), nullable=True),
    sa.Column('resume_path', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hired_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panel_id'], ['interview_panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['recruitment_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_application_date'), ['application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_status'), ['status'], unique=False)

    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('acceptance_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bonuses_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_bonuses_bonus_type_id', 'bonus_types', ['bonus_type_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bank_account_no', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('shift_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('duty_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('employee_type', sa.String(length=20), nullable=False, server_default=sa.text("'Academics'")))
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=300), nullable=True))
        batch_op.create_foreign_key('fk_employees_grade_id', 'grades', ['grade_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entitlement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('days_applied', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_leaves_entitlement_id', 'leave_entitlements', ['entitlement_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    with op.batch_alter_table('recruitment_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=30), nullable=False, server_default=sa.text("'full_time'")))
        batch_op.add_column(sa.Column('job_categories', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('job_location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
        batch_op.add_column(sa.Column('hr_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_salary_advances_request_date'), ['request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_advances_status'), ['status'], unique=False)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('violation_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=False, server_default=sa.text("'pending'")))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decided_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_violations_approval_status'), ['approval_status'], unique=False)
        batch_op.create_foreign_key('fk_violations_decided_by_id', 'users', ['decided_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_violations_violation_type_id', 'violation_types', ['violation_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_violations_violation_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_violations_decided_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_violations_approval_status'))
        batch_op.drop_column('decided_at')
        batch_op.drop_column('decided_by_id')
        batch_op.drop_column('remarks')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('violation_type_id')

    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_advances_status'))
        batch_op.drop_index(batch_op.f('ix_salary_advances_request_date'))
        batch_op.drop_column('decided_at')
        batch_op.drop_column('hr_remarks')
        batch_op.drop_column('request_date')

    with op.batch_alter_table('recruitment_requests', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('job_location')
        batch_op.drop_column('skills')
        batch_op.drop_column('job_categories')
        batch_op.drop_column('job_type')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leaves_entitlement_id', type_='foreignkey')
        batch_op.drop_column('days_applied')
        batch_op.drop_column('entitlement_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_grade_id', type_='foreignkey')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('grade_id')
        batch_op.drop_column('employee_type')
        batch_op.drop_column('duty_hours')
        batch_op.drop_column('shift_code')
        batch_op.drop_column('bank_account_no')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('religion')
        batch_op.drop_column('mother_name')

    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bonuses_bonus_type_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bonuses_status'))
        batch_op.drop_column('decided_at')
        batch_op.drop_column('acceptance_date')
        batch_op.drop_column('bonus_type_id')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_status'))
        batch_op.drop_index(batch_op.f('ix_job_applications_request_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_application_date'))

    op.drop_table('job_applications')
    with op.batch_alter_table('attendance_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_change_requests_attendance_date'))

    op.drop_table('attendance_change_requests')
    with op.batch_alter_table('staff_complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_staff_complaints_is_secret'))
        batch_op.drop_index(batch_op.f('ix_staff_complaints_employee_id'))

    op.drop_table('staff_complaints')
    with op.batch_alter_table('progress_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_notes_working_date'))
        batch_op.drop_index(batch_op.f('ix_progress_notes_employee_id'))

    op.drop_table('progress_notes')
    with op.batch_alter_table('leave_entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_entitlements_employee_id'))

    op.drop_table('leave_entitlements')
    with op.batch_alter_table('employee_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_requests_status'))
        batch_op.drop_index(batch_op.f('ix_employee_requests_request_date'))
        batch_op.drop_index(batch_op.f('ix_employee_requests_employee_id'))

    op.drop_table('employee_requests')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))

    op.drop_table('attachments')
    op.drop_table('violation_types')
    op.drop_table('interview_panels')
    op.drop_table('hr_downloads')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_holiday_date'))

    op.drop_table('holidays')
    op.drop_table('grades')
    op.drop_table('bonus_types')
    # ### end Alembic commands ###
