"""complaint lifecycle: findings, ladder, parent confirmation, contacts

Adds the investigation finding, the complaint subject, the escalation ladder level, the parent-confirmation loop
(confirmation, reopen and closure fields) and the parent_contacts table. See docs/COMPLAINTS.md.

Revision ID: 9cde39c9bd43
Revises: 6eb79b7d42ee
Create Date: 2026-10-09 02:37:31.017520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cde39c9bd43'
down_revision: Union[str, Sequence[str], None] = '6eb79b7d42ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_contacts',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('contacted_at', sa.DateTime(), nullable=False),
    sa.Column('contacted_by_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('parent_response', sa.Text(), nullable=True),
    sa.Column('satisfaction', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('agreed_action', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_task_id', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_attachment_id', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('referral_mentioned', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contacted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['follow_up_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recording_attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_contacts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_contacts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_contacts_contacted_at'), ['contacted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_contacts_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('case_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), nullable=False, server_default=sa.text("'comment'")))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('against_employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('against_department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('against_process', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('investigation_finding', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('finding_outcome', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('findings_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('findings_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('root_cause_category', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('corrective_action', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preventive_action', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('escalation_level', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('confirmation_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('confirmed_by_parent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('closure_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('reopen_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('reopened_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('repeat_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cases_against_employee_id'), ['against_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_root_cause_category'), ['root_cause_category'], unique=False)
        batch_op.create_foreign_key('fk_cases_findings_by_id', 'users', ['findings_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_cases_against_department_id', 'departments', ['against_department_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_cases_against_employee_id', 'employees', ['against_employee_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_cases_repeat_of_id', 'cases', ['repeat_of_id'], ['id'], ondelete='SET NULL')


    # A complaint about a teacher is a complaint against that teacher's employee record (docs/COMPLAINTS.md): fill it
    # in for complaints recorded before this revision, so they appear in the teacher's complaint history.
    op.execute(
        "UPDATE cases SET against_employee_id = (SELECT teachers.employee_id FROM teachers WHERE teachers.id = cases.teacher_id) "
        "WHERE case_type = 'complaint' AND teacher_id IS NOT NULL AND against_employee_id IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cases_repeat_of_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cases_against_employee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cases_against_department_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cases_findings_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cases_root_cause_category'))
        batch_op.drop_index(batch_op.f('ix_cases_against_employee_id'))
        batch_op.drop_column('repeat_of_id')
        batch_op.drop_column('reopened_at')
        batch_op.drop_column('reopen_count')
        batch_op.drop_column('closure_type')
        batch_op.drop_column('confirmed_by_parent')
        batch_op.drop_column('confirmation_attempts')
        batch_op.drop_column('confirmation_due_at')
        batch_op.drop_column('escalation_level')
        batch_op.drop_column('preventive_action')
        batch_op.drop_column('corrective_action')
        batch_op.drop_column('root_cause_category')
        batch_op.drop_column('findings_at')
        batch_op.drop_column('findings_by_id')
        batch_op.drop_column('severity')
        batch_op.drop_column('finding_outcome')
        batch_op.drop_column('investigation_finding')
        batch_op.drop_column('against_process')
        batch_op.drop_column('against_department_id')
        batch_op.drop_column('against_employee_id')
        batch_op.drop_column('incident_date')

    with op.batch_alter_table('case_comments', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('parent_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_contacts_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_contacts_contacted_at'))
        batch_op.drop_index(batch_op.f('ix_parent_contacts_client_id'))
        batch_op.drop_index(batch_op.f('ix_parent_contacts_case_id'))

    op.drop_table('parent_contacts')
    # ### end Alembic commands ###
