"""64-bit file sizes for recordings, backups, file assets and attachments

A recording's size (duration x 180 KB/s) passes 2^31 bytes for a class longer than about 3h20m, and PostgreSQL
refused it ("integer out of range"), which stopped the 9 Oct 2026 deploys. Backups and uploads can pass 2 GB too.

Revision ID: a4d438bbecd9
Revises: 9cde39c9bd43
Create Date: 2026-10-09 05:14:22.881137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d438bbecd9'
down_revision: Union[str, Sequence[str], None] = '9cde39c9bd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
