"""ERP parity walk: contract end, staff notices, feedback questions, Confido agents

Revision ID: cd82be2cce8f
Revises: 2d78aefa0e3f
Create Date: 2026-09-17 03:27:12.140240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd82be2cce8f'
down_revision: Union[str, Sequence[str], None] = '2d78aefa0e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_questions',
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('question_urdu', sa.String(length=300), nullable=True),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_questions_applies_to'), ['applies_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_questions_status'), ['status'], unique=False)

    op.create_table('agent_licenses',
    sa.Column('license_key', sa.String(length=64), nullable=False),
    sa.Column('issued_to_user_id', sa.Integer(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_licenses_license_key'), ['license_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_licenses_status'), ['status'], unique=False)

    op.create_table('staff_notices',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_notices_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_notices_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_notices_status'), ['status'], unique=False)

    op.create_table('agent_devices',
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('machine_name', sa.String(length=120), nullable=False),
    sa.Column('machine_id', sa.String(length=120), nullable=False),
    sa.Column('os_name', sa.String(length=80), nullable=True),
    sa.Column('agent_version', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_id'], ['agent_licenses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_devices_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_devices_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_devices_machine_id'), ['machine_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_devices_status'), ['status'], unique=False)

    op.create_table('agent_screenshots',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['agent_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_screenshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_screenshots_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_screenshots_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_end_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employees_contract_end_date'), ['contract_end_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_contract_end_date'))
        batch_op.drop_column('contract_end_date')

    with op.batch_alter_table('agent_screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_screenshots_employee_id'))
        batch_op.drop_index(batch_op.f('ix_agent_screenshots_device_id'))
        batch_op.drop_index(batch_op.f('ix_agent_screenshots_captured_at'))

    op.drop_table('agent_screenshots')
    with op.batch_alter_table('agent_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_devices_status'))
        batch_op.drop_index(batch_op.f('ix_agent_devices_machine_id'))
        batch_op.drop_index(batch_op.f('ix_agent_devices_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_agent_devices_employee_id'))

    op.drop_table('agent_devices')
    with op.batch_alter_table('staff_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_notices_status'))
        batch_op.drop_index(batch_op.f('ix_staff_notices_start_date'))
        batch_op.drop_index(batch_op.f('ix_staff_notices_end_date'))

    op.drop_table('staff_notices')
    with op.batch_alter_table('agent_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_licenses_status'))
        batch_op.drop_index(batch_op.f('ix_agent_licenses_license_key'))

    op.drop_table('agent_licenses')
    with op.batch_alter_table('feedback_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_questions_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_questions_applies_to'))

    op.drop_table('feedback_questions')
    # ### end Alembic commands ###
