"""ERP parity: session slots, academic config, client requests, class management, ledger additions, QA calls

Revision ID: dee1fc82982b
Revises: 6d42e23b4b1a
Create Date: 2026-09-13 20:13:00.078361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee1fc82982b'
down_revision: Union[str, Sequence[str], None] = '6d42e23b4b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary_accounts',
    sa.Column('payment_mode', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('account_details', sa.String(length=300), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_addition_types',
    sa.Column('addition_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_issue_types',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_review_parameters',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_rating', sa.Integer(), nullable=False),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_slots',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_no', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_slots_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_slots_start_time'), ['start_time'], unique=False)

    op.create_table('assessment_definitions',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_academic_groups',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pseudo_name', sa.String(length=80), nullable=True),
    sa.Column('shift_group', sa.String(length=20), nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank',
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_arrangements',
    sa.Column('from_teacher_id', sa.Integer(), nullable=False),
    sa.Column('to_teacher_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('session_category', sa.String(length=20), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['session_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_arrangements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_arrangements_from_date'), ['from_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_arrangements_from_teacher_id'), ['from_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_arrangements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_arrangements_to_teacher_id'), ['to_teacher_id'], unique=False)

    op.create_table('client_contacts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_contacts_client_id'), ['client_id'], unique=False)

    op.create_table('client_credentials',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('login', sa.String(length=200), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_credentials_client_id'), ['client_id'], unique=False)

    op.create_table('referred_contacts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referred_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referred_contacts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referred_contacts_status'), ['status'], unique=False)

    op.create_table('teams_users',
    sa.Column('person_type', sa.String(length=10), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('teams_email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_users_person_type'), ['person_type'], unique=False)

    op.create_table('ledger_additions',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('currency_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lc_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('addition_type', sa.String(length=40), nullable=False),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('addition_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_employee_id', sa.Integer(), nullable=True),
    sa.Column('billing_rep_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_rep_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_additions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_additions_addition_date'), ['addition_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_additions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_additions_status'), ['status'], unique=False)

    op.create_table('invoice_addition_rules',
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('addition_type_id', sa.Integer(), nullable=False),
    sa.Column('implementation_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auto_assigned', sa.Boolean(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addition_type_id'], ['invoice_addition_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_change_requests',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('current_teacher_id', sa.Integer(), nullable=True),
    sa.Column('new_teacher_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_remarks', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_change_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_change_requests_status'), ['status'], unique=False)

    op.create_table('time_change_requests',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('current_slot_id', sa.Integer(), nullable=True),
    sa.Column('new_slot_id', sa.Integer(), nullable=True),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_remarks', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_slot_id'], ['session_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_slot_id'], ['session_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_change_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_change_requests_status'), ['status'], unique=False)

    op.create_table('class_activities',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('page_no', sa.String(length=40), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_activities_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_activities_student_id'), ['student_id'], unique=False)

    op.create_table('class_queries',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_queries_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_queries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_queries_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('reschedule_requests',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('old_date', sa.Date(), nullable=False),
    sa.Column('new_date', sa.Date(), nullable=False),
    sa.Column('old_start_time', sa.Time(), nullable=False),
    sa.Column('new_start_time', sa.Time(), nullable=False),
    sa.Column('old_teacher_id', sa.Integer(), nullable=True),
    sa.Column('new_teacher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('new_session_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_session_id'], ['class_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reschedule_requests_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reschedule_requests_status'), ['status'], unique=False)

    op.create_table('call_records',
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('recording_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_status', sa.String(length=20), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('review_state', sa.String(length=20), nullable=False),
    sa.Column('qa_review_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qa_review_id'], ['qa_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_recording_date'), ['recording_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_review_state'), ['review_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'active'")))
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=True))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_type', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('company_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=False, server_default=sa.text("'pending'")))
        batch_op.create_index(batch_op.f('ix_cases_approval_status'), ['approval_status'], unique=False)

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_available_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('arrangement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('done_by_teacher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_class_sessions_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_foreign_key('fk_class_sessions_subscription_id', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_class_sessions_done_by_teacher_id', 'teachers', ['done_by_teacher_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_class_sessions_arrangement_id', 'class_arrangements', ['arrangement_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_class_sessions_slot_id', 'session_slots', ['slot_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_recurrence', sa.String(length=20), nullable=False, server_default=sa.text("'monthly'")))
        batch_op.add_column(sa.Column('legacy_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('shift', sa.String(length=20), nullable=False, server_default=sa.text("'night'")))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('referred_by_client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_remarks', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('academic_manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_added_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_legacy_code'), ['legacy_code'], unique=False)
        batch_op.create_foreign_key('fk_clients_academic_manager_id', 'users', ['academic_manager_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_clients_lead_added_by_id', 'users', ['lead_added_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_clients_academic_group_id', 'client_academic_groups', ['academic_group_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_clients_converted_by_id', 'users', ['converted_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_clients_referred_by_client_id', 'clients', ['referred_by_client_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', sa.String(length=40), nullable=False, server_default=sa.text("'Islamic Courses'")))
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('attendance_required', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('curriculum_link', sa.String(length=300), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('sort_no', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_evaluations_assessment_id', 'assessment_definitions', ['assessment_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_source', sa.String(length=20), nullable=False, server_default=sa.text("'client_portal'")))
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_feedback_session_id', 'class_sessions', ['session_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subs_total', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('subs_discount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('subs_tax', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('confirmed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_bulk', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_foreign_key('fk_invoices_confirmed_by_id', 'users', ['confirmed_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_for_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('apply_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leave_detail', sa.Text(), nullable=True))

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_days', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('max_days', sa.Integer(), nullable=False, server_default=sa.text('5')))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('receiving_destination', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('beneficiary_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_rep_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_receipt_date'), ['receipt_date'], unique=False)
        batch_op.create_foreign_key('fk_payments_confirmed_by_id', 'users', ['confirmed_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_payments_billing_rep_id', 'users', ['billing_rep_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_payments_beneficiary_account_id', 'beneficiary_accounts', ['beneficiary_account_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_record_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parameter_scores', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('issues', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_qa_reviews_call_record_id'), ['call_record_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('trial_days', sa.Integer(), nullable=False, server_default=sa.text('3')))
        batch_op.add_column(sa.Column('legacy_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('drop_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_legacy_code'), ['legacy_code'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('days_of_week', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('language', sa.String(length=30), nullable=False, server_default=sa.text("'English'")))
        batch_op.add_column(sa.Column('course_method', sa.String(length=20), nullable=False, server_default=sa.text("'one_on_one'")))
        batch_op.add_column(sa.Column('session_category', sa.String(length=20), nullable=False, server_default=sa.text("'30 Minutes'")))
        batch_op.add_column(sa.Column('session_type', sa.String(length=30), nullable=False, server_default=sa.text("'Job Time Session'")))
        batch_op.add_column(sa.Column('trial_days', sa.Integer(), nullable=False, server_default=sa.text('3')))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('books', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('follow_up_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_slot_id'), ['slot_id'], unique=False)
        batch_op.create_foreign_key('fk_subscriptions_slot_id', 'session_slots', ['slot_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_subscriptions_supervisor_id', 'users', ['supervisor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_supervisor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscriptions_slot_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscriptions_slot_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_follow_up_date'))
        batch_op.drop_column('follow_up_date')
        batch_op.drop_column('books')
        batch_op.drop_column('supervisor_id')
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('remarks')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('trial_days')
        batch_op.drop_column('session_type')
        batch_op.drop_column('session_category')
        batch_op.drop_column('course_method')
        batch_op.drop_column('language')
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('slot_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_legacy_code'))
        batch_op.drop_column('photo_path')
        batch_op.drop_column('grade')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('drop_date')
        batch_op.drop_column('legacy_code')
        batch_op.drop_column('trial_days')
        batch_op.drop_column('email')

    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reviews_call_record_id'))
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('issues')
        batch_op.drop_column('parameter_scores')
        batch_op.drop_column('remarks')
        batch_op.drop_column('overall_rating')
        batch_op.drop_column('call_record_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_beneficiary_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_billing_rep_id', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_confirmed_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_receipt_date'))
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by_id')
        batch_op.drop_column('billing_rep_id')
        batch_op.drop_column('beneficiary_account_id')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('receiving_destination')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('receipt_date')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('max_days')
        batch_op.drop_column('min_days')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('leave_detail')
        batch_op.drop_column('apply_date')
        batch_op.drop_column('leave_for_all')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_confirmed_by_id', type_='foreignkey')
        batch_op.drop_column('is_bulk')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by_id')
        batch_op.drop_column('subs_tax')
        batch_op.drop_column('subs_discount')
        batch_op.drop_column('subs_total')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_session_id', type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('feedback_source')

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evaluations_assessment_id', type_='foreignkey')
        batch_op.drop_column('due_date')
        batch_op.drop_column('is_manual')
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('sort_no')
        batch_op.drop_column('father_name')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('curriculum_link')
        batch_op.drop_column('attendance_required')
        batch_op.drop_column('fee')
        batch_op.drop_column('course_type')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_referred_by_client_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clients_converted_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clients_academic_group_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clients_lead_added_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_clients_academic_manager_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_legacy_code'))
        batch_op.drop_column('photo_path')
        batch_op.drop_column('converted_at')
        batch_op.drop_column('converted_by_id')
        batch_op.drop_column('lead_added_by_id')
        batch_op.drop_column('academic_group_id')
        batch_op.drop_column('academic_manager_id')
        batch_op.drop_column('status_remarks')
        batch_op.drop_column('referred_by_client_id')
        batch_op.drop_column('state')
        batch_op.drop_column('shift')
        batch_op.drop_column('opening_balance')
        batch_op.drop_column('legacy_code')
        batch_op.drop_column('fee_recurrence')

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_sessions_slot_id', type_='foreignkey')
        batch_op.drop_constraint('fk_class_sessions_arrangement_id', type_='foreignkey')
        batch_op.drop_constraint('fk_class_sessions_done_by_teacher_id', type_='foreignkey')
        batch_op.drop_constraint('fk_class_sessions_subscription_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_class_sessions_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_slot_id'))
        batch_op.drop_column('activity_updated_at')
        batch_op.drop_column('done_by_teacher_id')
        batch_op.drop_column('arrangement_id')
        batch_op.drop_column('teacher_available_at')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('slot_id')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_approval_status'))
        batch_op.drop_column('approval_status')
        batch_op.drop_column('company_response')
        batch_op.drop_column('complaint_type')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('status')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_source'))
        batch_op.drop_index(batch_op.f('ix_call_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_review_state'))
        batch_op.drop_index(batch_op.f('ix_call_records_recording_date'))

    op.drop_table('call_records')
    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reschedule_requests_status'))
        batch_op.drop_index(batch_op.f('ix_reschedule_requests_session_id'))

    op.drop_table('reschedule_requests')
    with op.batch_alter_table('class_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_queries_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_queries_status'))
        batch_op.drop_index(batch_op.f('ix_class_queries_session_id'))

    op.drop_table('class_queries')
    with op.batch_alter_table('class_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_activities_student_id'))
        batch_op.drop_index(batch_op.f('ix_class_activities_session_id'))

    op.drop_table('class_activities')
    with op.batch_alter_table('time_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_time_change_requests_client_id'))

    op.drop_table('time_change_requests')
    with op.batch_alter_table('teacher_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_change_requests_status'))
        batch_op.drop_index(batch_op.f('ix_teacher_change_requests_client_id'))

    op.drop_table('teacher_change_requests')
    op.drop_table('invoice_addition_rules')
    with op.batch_alter_table('ledger_additions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_additions_status'))
        batch_op.drop_index(batch_op.f('ix_ledger_additions_client_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_additions_addition_date'))

    op.drop_table('ledger_additions')
    with op.batch_alter_table('teams_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_users_person_type'))

    op.drop_table('teams_users')
    with op.batch_alter_table('referred_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referred_contacts_status'))
        batch_op.drop_index(batch_op.f('ix_referred_contacts_client_id'))

    op.drop_table('referred_contacts')
    with op.batch_alter_table('client_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_credentials_client_id'))

    op.drop_table('client_credentials')
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_contacts_client_id'))

    op.drop_table('client_contacts')
    with op.batch_alter_table('class_arrangements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_arrangements_to_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_arrangements_status'))
        batch_op.drop_index(batch_op.f('ix_class_arrangements_from_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_arrangements_from_date'))

    op.drop_table('class_arrangements')
    op.drop_table('question_bank')
    op.drop_table('client_academic_groups')
    op.drop_table('assessment_definitions')
    with op.batch_alter_table('session_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_session_slots_category'))

    op.drop_table('session_slots')
    op.drop_table('qa_review_parameters')
    op.drop_table('qa_issue_types')
    op.drop_table('invoice_addition_types')
    op.drop_table('beneficiary_accounts')
    # ### end Alembic commands ###
